'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InkedWeb_capture_24_4_2023_215840_blogger_googleusercontent_com_LI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InkedWeb capture_24-4-2023_215840_blogger.googleusercontent.com_LI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InkedWeb_capture_24_4_2023_2204_blogger_googleusercontent_com_LI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InkedWeb capture_24-4-2023_2204_blogger.googleusercontent.com_LI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InkedWeb_capture_24_4_2023_2218_blogger_googleusercontent_com_LI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InkedWeb capture_24-4-2023_2218_blogger.googleusercontent.com_LI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InkedWeb_capture_24_4_2023_22237_blogger_googleusercontent_com_LI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InkedWeb capture_24-4-2023_22237_blogger.googleusercontent.com_LI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InkedWeb_capture_24_4_2023_22345_blogger_googleusercontent_com_LI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InkedWeb capture_24-4-2023_22345_blogger.googleusercontent.com_LI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property visual_studio_1440_x_900_wallpaper_hkcbl8cfvbtawaqh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("visual-studio-1440-x-900-wallpaper-hkcbl8cfvbtawaqh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_24_4_2023_232618_wallpapercave_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_24-4-2023_232618_wallpapercave.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_24_4_2023_23945_www_reddit_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_24-4-2023_23945_www.reddit.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_3_5_2023_8424_www_123rf_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_3-5-2023_8424_www.123rf.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_3_5_2023_91750_www_dreamstime_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_3-5-2023_91750_www.dreamstime.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_3_5_2023_92333_www_dreamstime_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_3-5-2023_92333_www.dreamstime.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_3_5_2023_93230_wallpapersafari_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_3-5-2023_93230_wallpapersafari.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_30_4_2023_174354_blogger_googleusercontent_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_30-4-2023_174354_blogger.googleusercontent.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_30_4_2023_175822_blogger_googleusercontent_com_PhotoRoom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_30-4-2023_175822_blogger.googleusercontent.com-PhotoRoom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_30_4_2023_181025_www_pinterest_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_30-4-2023_181025_www.pinterest.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_30_4_2023_92556_www_freepik_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_30-4-2023_92556_www.freepik.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Web_capture_30_4_2023_9485_phppot_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web capture_30-4-2023_9485_phppot.com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
